apiVersion: apps/v1
kind: Deployment
metadata:
  name: delay-api-dep
  labels:
    app: delay-api-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delay-api-dep
  template:
    metadata:
      labels:
        app: delay-api-dep
    spec:
      containers:
      - name: delay-api
        image: gireeshp/delay-api:1.0
        resources:
          limits:
            cpu: 250m
          requests:
            cpu: 100m
        ports:
        - containerPort: 8081