apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: delay-api
spec:
  backend:
    serviceName: delay-api
    servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: delay-api
  labels:
    app: delay-api
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8081
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8081
    protocol: TCP
    name: https
  selector:
    app: delay-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delay-api
  labels:
    app: delay-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delay-api
  template:
    metadata:
      labels:
        app: delay-api
    spec:
      containers:
      - name: delay-api
        image: gireeshp/delay-api:1.0
        resources:
          limits:
            cpu: 250m
          requests:
            cpu: 100m
        ports:
        - containerPort: 8081
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: delay-api
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: delay-api
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 25